# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sp-talent-finder-app-dev

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sptalentfinderregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1760006e3e1d463f84bc2a43cc791bf5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fc0e5aacf9d24a4a91b2f6090428ee34 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sptalentfinderregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1760006e3e1d463f84bc2a43cc791bf5 }}/sptalentfinderregistry:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sp-talent-finder-app-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b63a1a326894f969acf5b70b6454537 }}
        images: 'sptalentfinderregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1760006e3e1d463f84bc2a43cc791bf5 }}/sptalentfinderregistry:${{ github.sha }}'